#!/bin/csh

#SBATCH -N $NB_NODES                # Nombre de noeuds (1 noeud = 16 procs)
#SBATCH -n $NB_PROCS                # Nombre de processeurs total // Essayer au moins 16 sinon ajout de ntasks-per-nodes
#SBATCH --ntasks-per-node=36
#SBATCH -J waLBerla          # Nom du job dans la file de soumission
#SBATCH -e job.err.%J
#SBATCH -o job.out.%J
#SBATCH -p standard 
#SBATCH --wckey MMP04001    # Numero du projet
#SBATCH -t 48:00:00 

ml foss/2018b
ml CUDA/10.0.130

mpirun -np $NB_PROCS ./../../TurbineLBM_CPU_$KERNEL input_mexico.prm
